version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'npm dependencies'
    commit-message:
      prefix: 'npm'
    assignees:
      - 'gregoranders'
    target-branch: 'development'
