version: '2'
checks:
  file-lines:
    config:
      threshold: 1000
plugins:
  editorconfig:
    enabled: false
  tslint:
    enabled: false
  eslint:
    enabled: true
    config:
      config: .eslintrc-cc.json
    extensions:
      - .es6
      - .js
      - .jsx
      - .ts
      - .tsx
      - .mjs
  fixme:
    enabled: true
  git-legal:
    enabled: true
exclude_patterns:
  - '**/.github'
  - '**/.circleci'
  - '**/.vscode'
  - '**/*.svg'
  - '**/*.spec.ts'
  - '**/dist'
  - '**/temp'
  - '**/test'
  - '**/docs'
  - '**/node_modules/'
  - '**/.husky'
  - '**/commitlint.config.js'
